[package]
name = "rshell"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
crossterm = "0.27"
libc = "0.2.177"
whoami = "1.6.1"

nix = { version = "0.30.1", features = ["signal", "process"] }
